name: Handeling Issues
on: issues
jobs:
    output-info:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Output Issue event details
              run: echo "${{ toJson(github.event)}}"